pretrain:
  # visual_backbone: './exp/pretrain_resnet18/vision_backbone.pth'
  # tactile_backbone: './exp/pretrain_resnet18/touch_backbone.pth'
  # audio_backbone: './exp/pretrain_resnet18/audio_backbone.pth'

  visual_backbone: './exp/rt/vision/bst.pth'
  tactile_backbone: './exp/rt/touch_4/bst.pth'
  audio_backbone: './exp/rt/audio_4/bst.pth'